DROP TABLE Member;
DROP TABLE Item;

CREATE TABLE Member(
	Name VARCHAR(20) NOT NULL,
	Password CHAR(128) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	Guild BOOLEAN NOT NULL,
	PRIMARY KEY(Email)
);

CREATE TABLE Item(
	Name VARCHAR(30) NOT NULL,
	Type VARCHAR(30) NOT NULL,
	Category VARCHAR(30) NOT NULL,
	Price NUMERIC(7,0) NOT NULL,
	Attack NUMERIC(3,0),
	Defense NUMERIC(3,0),
	Magic NUMERIC(3,0),
	Resistance NUMERIC(3,0),
	Speed NUMERIC(3,0),
	Move NUMERIC(3,0),
	Jump NUMERIC(3,0),
	Evasion NUMERIC(3,0),
	Path VARCHAR(255),
	PRIMARY KEY(Name)
);

